version: "3.9"
services:

  ###### name service ######
  skaimsginterface_service:
    #### name image  & container ####
    image: ${BASENAME}_img_${PARENTDIR}
    container_name: ${BASENAME}_instance_${PARENTDIR}

    #### command to keep container alive ####
    command: tail -F /dev/null

    #### build Dockerfile and pass build args ####
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ARCH: ${ARCH}

    #### volumes and mappings ####
    volumes:
      - ${MAP_DISPLAY}
      - ${MAP_SSH}
      - ${MAP_TIMEZONE}
      - ./package:/root/package
      
    network_mode: "host" # uses host network stack 
    working_dir: /root/package/examples
    